name: Backend Deployment to Azure

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 'v21.5.0'

      - name: Install Dependencies
        run: npm install

      - name: List NPM Scripts
        run: npm run

      - name: Build
        run: npm run build
        
      - name: Deploy to Azure Web App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'MovieMeter'
          publish-profile: ${{ secrets.AZUREWEBAPPPUBLISHPROFILE }}
          package: dist
          
        