  name: Deploy to Azure Web App Service

  on:
    push:
      branches:
        - Deployment

  jobs:
    build-and-deploy:
      runs-on: ubuntu-latest

      steps:
        -name: Checkout the code
        uses: actions/checkout@v2
        -name: Setup Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
        -name: Install dependencies
        run: npm install
        -name: Deploy to Azure Web App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'MovieMeter'
          publish-profile: ${{ secrets.azureWebappPublishProfile }}
          
        