name: Backend Deployment to Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Clear NPM cache
        run: npm cache clean --force

      - name: Install Dependencies
        run: npm install --verbose

      - name: Display package.json
        run: cat package.json

      - name: List available npm scripts
        run: npm run

      - name: Build
        run: npm run build

      - name: Deploy to Azure Web App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'MovieMeter'
          publish-profile: ${{ secrets.AZUREWEBAPPPUBLISHPROFILE }}
          package: dist   