name: MovieMeter - Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: back-end

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "back-end/package-lock.json"
      - name: Install dependencies
        run: npm ci
        working-directory: back-end
      - name: Build project
        run: npm run build --if-present
        working-directory: back-end
      - name: test formatting
        run: | 
            npm test --if-present  
            npm run coverage --if-present
        working-directory: back-end