name: MovieMeter - Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: frontend

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"
      - name: npm ci, build, and test
        env:
          NEXTPUBLICAWSS3REGION: ${{secrets.NEXTPUBLICAWSS3REGION}}
          NEXTPUBLICAWSS3ACCESSKEYID: ${{secrets.NEXTPUBLICAWSS3ACCESSKEYID}}
          NEXTPUBLICAWSS3SECRETACCESSKEYID: ${{secrets.NEXTPUBLICAWSS3SECRETACCESSKEYID}}
          NEXTPUBLICAWSS3BUCKETNAME: ${{secrets.NEXTPUBLICAWSS3BUCKETNAME}}
        run: |
          npm ci
          npm run build --if-present
          npm test --if-present  
          npm run coverage --if-present
        working-directory: frontend
